from enum import Enum
from typing import Any, Dict, Generic, List, Literal, Optional, TypeVar, Union

from pydantic import BaseModel, Field

# =============================================================================
# Legacy Types (Backward Compatibility)
# =============================================================================


class Message(BaseModel):
    """Base message type for conversation history."""

    role: Literal["system", "user", "assistant", "tool"]
    content: Optional[str] = ""
    name: Optional[str] = None
    tool_calls: Optional[List[Dict[str, Any]]] = None
    tool_call_id: Optional[str] = None
    reasoning_content: Optional[str] = None


class StreamChunk(BaseModel):
    """Legacy stream chunk - deprecated in favor of StreamPart types."""

    content: str
    finish_reason: Optional[str] = None


class LLMResponse(BaseModel):
    """Response from LLM provider."""

    content: Optional[str]
    tool_calls: Optional[List[Dict[str, Any]]] = None
    raw_response: Optional[object] = None
    usage: Optional[dict] = None


# =============================================================================
# UI Message Part State Enums
# =============================================================================


class TextPartState(str, Enum):
    """States for text content parts."""

    STREAMING = "streaming"
    DONE = "done"


class ToolPartState(str, Enum):
    """States for tool execution lifecycle.

    States:
        INPUT_STREAMING: Tool arguments being generated by LLM
        INPUT_AVAILABLE: Arguments complete, ready for execution
        OUTPUT_AVAILABLE: Tool executed, result available
        OUTPUT_ERROR: Tool execution failed
        APPROVAL_REQUESTED: Waiting for user approval
    """

    INPUT_STREAMING = "input-streaming"
    INPUT_AVAILABLE = "input-available"
    OUTPUT_AVAILABLE = "output-available"
    OUTPUT_ERROR = "output-error"
    APPROVAL_REQUESTED = "approval-requested"


# =============================================================================
# UI Message Part Types
# =============================================================================


class TextUIPart(BaseModel):
    """Text content with streaming state."""

    type: Literal["text"] = "text"
    text: str
    state: Optional[TextPartState] = None


class ReasoningUIPart(BaseModel):
    """Agent thinking/reasoning trace."""

    type: Literal["reasoning"] = "reasoning"
    text: str
    state: Optional[TextPartState] = None
    provider_metadata: Optional[Dict[str, Any]] = None


class ToolUIPart(BaseModel):
    """Tool invocation and result representation.

    This part represents the complete lifecycle of a tool call:
    1. INPUT_STREAMING: Tool arguments being generated by LLM
    2. INPUT_AVAILABLE: Arguments complete, ready for execution
    3. OUTPUT_AVAILABLE: Tool executed, result available
    4. OUTPUT_ERROR: Tool execution failed
    5. APPROVAL_REQUESTED: Waiting for user to approve execution
    """

    type: str = Field(..., description="Format: tool-{tool_name}")
    tool_call_id: str
    tool_name: str
    state: ToolPartState

    # Input data (when state is INPUT_* or OUTPUT_*)
    input: Optional[Dict[str, Any]] = None

    # Output data (when state is OUTPUT_AVAILABLE)
    output: Optional[Any] = None

    # Error text (when state is OUTPUT_ERROR)
    error_text: Optional[str] = None

    # Approval data (when state is APPROVAL_REQUESTED)
    approval_id: Optional[str] = None

    # Execution flag
    provider_executed: Optional[bool] = None


class FileUIPart(BaseModel):
    """File or image attachment."""

    type: Literal["file"] = "file"
    media_type: str = Field(..., description="IANA media type (e.g., image/png)")
    filename: Optional[str] = None
    url: str = Field(..., description="Can be URL or data URL (base64)")


class DataUIPart(BaseModel):
    """Custom data part for structured data.

    This allows passing arbitrary structured data to the frontend
    for custom UI components.
    """

    type: str = Field(..., description="Format: data-{data_name}")
    id: Optional[str] = None
    data: Dict[str, Any]


class StepStartUIPart(BaseModel):
    """Marker for step boundary in multi-step tool execution."""

    type: Literal["step-start"] = "step-start"


# Union type for all UI message parts
UIMessagePart = Union[
    TextUIPart,
    ReasoningUIPart,
    ToolUIPart,
    FileUIPart,
    DataUIPart,
    StepStartUIPart,
]


# =============================================================================
# UI Message Type
# =============================================================================

METADATA = TypeVar("METADATA", bound=BaseModel)
DATA_PARTS = TypeVar("DATA_PARTS", bound=BaseModel)
TOOLS = TypeVar("TOOLS", bound=BaseModel)


class UIMessage(BaseModel, Generic[METADATA, DATA_PARTS, TOOLS]):
    """UI Message - Complete message representation for frontend rendering.

    This is the single source of truth for application state, containing
    full message history including metadata, data parts, and contextual
    information for UI rendering.

    Generic Parameters:
        METADATA: Custom metadata type for additional message information
        DATA_PARTS: Custom data part types for structured components
        TOOLS: Tool definitions for type-safe tool interactions
    """

    id: str
    role: Literal["system", "user", "assistant"]
    metadata: Optional[METADATA] = None
    parts: List[UIMessagePart]


# =============================================================================
# Stream Part Types (for Provider-Level Streaming)
# =============================================================================


class TextStreamDelta(BaseModel):
    """Text delta in streaming response."""

    type: Literal["text"] = "text"
    text: str


class ReasoningStreamDelta(BaseModel):
    """Reasoning delta in streaming response."""

    type: Literal["reasoning"] = "reasoning"
    text: str


class ToolCallStreamStart(BaseModel):
    """Tool call streaming starts."""

    type: Literal["tool-call-streaming-start"] = "tool-call-streaming-start"
    tool_call_id: str
    tool_name: str


class ToolCallStreamDelta(BaseModel):
    """Tool call argument delta (streaming)."""

    type: Literal["tool-call-delta"] = "tool-call-delta"
    tool_call_id: str
    tool_name: str
    args_text_delta: str


class ToolCallComplete(BaseModel):
    """Complete tool call (when streaming is off or complete)."""

    type: Literal["tool-call"] = "tool-call"
    tool_call_id: str
    tool_name: str
    input: Dict[str, Any]


class ToolResultStream(BaseModel):
    """Tool execution result."""

    type: Literal["tool-result"] = "tool-result"
    tool_call_id: str
    tool_name: str
    input: Dict[str, Any]
    output: Any
    is_error: bool = False


# Union type for all stream parts
StreamPart = Union[
    TextStreamDelta,
    ReasoningStreamDelta,
    ToolCallStreamStart,
    ToolCallStreamDelta,
    ToolCallComplete,
    ToolResultStream,
]
